main/urls.py
from django.urls import path
from main.views import home, soon, profile, experiences, skills

app_name = "Story_4"

urlpatterns = [
    path('', home, name="home"),
    path('profile', profile, name="profile"),
    path('experiences', experiences, name="experiences"),
    path('skills', skills, name="skills")
]

personalweb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('story5/',include('story5.urls'))
]

story5/urls.py
from django.urls import path
from .views import jadwal, lihat_jadwal, delete

app_name = "Story_5"

urlpatterns = [
    path('', jadwal, name="jadwal"),
    path('lihat_jadwal/', lihat_jadwal, name="lihat_jadwal"),
    path('jadwal/<int:delete_id>', delete, name='delete')
]

main/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from datetime import datetime

class JadwalKegiatan(models.Model):
    nama = models.CharField(max_length=30)
    tempat = models.CharField(max_length=20)
    kategori = models.CharField(max_length=20)
    # hari = models.CharField(max_length=10)
    tanggal = models.DateField()
    waktu = models.TimeField()

    def __str__(self):
        return self.nama

story5/forms.py
from django import forms
from .models import JadwalKegiatan
# from bootstrap_datepicker_plus import DateTimePickerInput, TimePickerInput

class JadwalKegiatanForm(forms.ModelForm): 
    nama = forms.CharField(widget=forms.TextInput(
        attrs = {
                'type' : 'text'
                }
    ))
    tempat = forms.CharField(widget=forms.TextInput(
        attrs = {
                'type' : 'text'
                }
    ))
    kategori = forms.CharField(widget=forms.TextInput(
        attrs = {
                'type' : 'text'
                }
    ))
    # hari = forms.CharField(label="", widget=forms.TextInput(
    #     attrs = {
    #             'type' : 'text'
    #             }
    # ))
    tanggal = forms.DateField(widget=forms.DateInput(
        attrs = {
                'type' : 'date'        
                }
    ))
    waktu = forms.TimeField(widget=forms.DateInput(
        attrs = {
                'type' : 'time'        
                }
    ))


    class Meta:
        model = JadwalKegiatan
        fields="__all__"
        # fields= [
        #     'nama',
        #     'tempat',
        #     'kategori',
        #     'tanggal',
        #     'waktu',
        # ]

        # labels = {
        #     'nama':'Nama',
        #     'tempat':'Tempat',
        #     'kategori':'Kategori',
        #     'tanggal':'Tanggal',
        #     'waktu':'Waktu',
        # }

        # widgets = {
        #     'name':forms.CharField(
        #         attrs={
                    
        #         },
        #     ),
        #     'tempat': forms.CharField(
        #         attrs={
                    
        #         },
        #     ),
        #     'kategori': forms.CharField(
        #         attrs={

        #         },
        #     ),
        #     'tanggal':forms.DateInput(
        #         attrs={
        #             'type' : 'date',
        #         },
        #     ),
        #     'waktu':forms.TimeInput(
        #         attrs={
        #             'type' : 'time',
        #         },
        #     ),
        # }

        

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, "index.html")

def soon(request):
    return render(request, "soon.html")

def profile(request):
    return render(request, "profile.html")
    
def experiences(request):
    return render(request, "experiences.html")
    
def skills(request):
    return render(request, "skills.html")

story5/views.py
from django.shortcuts import render, redirect
from .forms import JadwalKegiatanForm
from .models import JadwalKegiatan

def jadwal(request):
    
    form = JadwalKegiatanForm(request.POST)
    # data = Jadwal_Kegiatan.objects.all()
    # context = {
    #     "formulir":form,
    #     "model":data
    # } 
    # if request.method == "POST" and form.is_valid():
    #     nama = form.cleaned_data['nama']
    #     tempat = form.cleaned_data['tempat']
    #     kategori = form.cleaned_data['kategori']
    #     hari = form.cleaned_data['hari']
    #     waktu = form.cleaned_data['waktu']

    #     model= Jadwal_Kegiatan(nama, tempat, kategori, hari, waktu)
    #     model.save()
    #     return render(request, 'jadwal.html', context)
    # return render(request, 'jadwal.html', {"formulir":form})


    if request.method == "POST" and form.is_valid():
        form.save()      
    return render(request, "jadwal.html", {"form": JadwalKegiatanForm()})

def lihat_jadwal(request):
    obj = JadwalKegiatan.objects.all()

    context = {
        'jadwals':obj
    }

    return render(request, 'lihat_jadwal.html', context)
def delete(request, delete_id):
    JadwalKegiatan.objects.filter(id=delete_id).delete()
    return redirect('/story5/lihat_jadwal')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>Meet Luqman!</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel='stylesheet' type='text/css' media='screen' href="{% static 'bootstrap.css' %}">
        <link rel='stylesheet' type='text/css' media='screen' href="{% static 'style.css' %}">
    </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{% url 'Story_4:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'Story_4:profile' %}">Profile</a>
            <a class="nav-item nav-link" href="{% url 'Story_4:experiences' %}">Experiences</a>
            <a class="nav-item nav-link" href="{% url 'Story_4:skills' %}">Skills</a>
            <a class="nav-item nav-link" href="{% url 'Story_4:home' %}#contact">Contact</a>
            <a class="nav-item nav-link" href="{% url 'Story_5:jadwal' %}">Buat Jadwal</a>
            <a class="nav-item nav-link" href="{% url 'Story_5:lihat_jadwal' %}">Lihat Jadwal</a>
            </div>
        </div>
    </nav>
    
    {% block body %}
        
    {% endblock body %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

main/templates/experiences.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div id="experiences">
        <h1 class="h1-title"><u>Experiences</u></h1>
        <div class="container-experiences"> 
            <div class="experience-set container-experiences">               
                    <span class="experiences-title"><h2>Education</h2></span>
                    <span class="experiences-item experience-set">Universitas Indonesia</span>
                    <span class="experiences-time">2018 - Present</span>
                    <span class="experiences-item experience-set">SMAN 8 Jakarta</span>
                    <span class="experiences-time">2015 - 2018</span>
            </div>
            <div class="experience-set container-experiences">
                    <span class="experiences-title"><h2>Organization and Comittee</h2></span>
                    <span class="experiences-item experience-set">DPM Fasilkom UI</span>
                    <span class="experiences-time">February 2019 - Present</span>
                    <span class="experiences-desc">as staff at Legal Comission</span>
                    <span class="experiences-item experience-set">FUKI Fasilkom UI</span>
                    <span class="experiences-time">February 2019 - Present</span>
                    <span class="experiences-desc">as staff at Islamic Learning Center Department</span>
                    <span class="experiences-item experience-set">Pemira IKM Fasilkom UI</span>
                    <span class="experiences-time">September 2019 - Present</span>
                    <span class="experiences-desc">as vice person in charge at Verification and Supervision division</span>
                    <span class="experiences-item experience-set">COMPFEST 11</span>
                    <span class="experiences-time">February 2019 - Present</span>
                    <span class="experiences-desc ">as staff at Innovative App Competition</span>
                    <span class="experiences-item experience-set">MTQ UI</span>
                    <span class="experiences-time">September 2019 - Present</span>
                    <span class="experiences-desc">as staff at Musabaqah Hifzhil Quran division</span>
            </div>
        </div>
    </div>    
{% endblock body %}
    

main/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div id="homepage">
    <div class="containers">
        <div class="backdrop">
            <div class="home-text">
            <h1><bold><u>Luqman Maulana Rizki</u></bold></h1>
            <h2>Personal Website</h2>
            </div>
        </div>
    </div>
</div>
<div id="contact">
    <div id="contact-card">
        <h1 class="h1-title"><b>Find Me More!</b></h1>
        <table class="contact-table">
            <tr>
                <td><a href="#"><img class="contact-logo" src="{% static 'email.png' %}" alt="My Email"></a></td>
                <td>luqmanmaulanar@gmail.com</td>
            </tr>
            <tr>
                <td><a href="https://www.linkedin.com/in/luqman-maulana-rizki-83545814a"><img class="contact-logo" src="{% static 'linkedin.png' %}" alt="My LinkedIn"></a></td>
                <td><a href="https://www.linkedin.com/in/luqman-maulana-rizki-83545814a">https://www.linkedin.com/in/luqman-maulana-rizki-83545814a</a></td>
            </tr>
            <tr>
                <td><a href="https://gitlab.com/Luqmanmaulana"><img class="contact-logo" src="{% static 'gitlab.png' %}" alt="My Gitlab"></a></td>
                <td><a href="https://gitlab.com/Luqmanmaulana">https://gitlab.com/Luqmanmaulana</a></td>
            </tr>
            <tr>
                <td><a href="https://instagram.com/luqman_maulana"><img class="contact-logo" src="{% static 'instagram.png' %}" alt="My Instagram"></a></td>
                <td><a href="https://instagram.com/luqman_maulana">luqman_maulana</a></td>
            </tr>
        </table>
    </div>
</div>
{% endblock body %}
    

main/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div id="profile">
    <h1 class="h1-title"><u>Profile</u></h1>
    <h2>"An energic, beginner developer"</h2>
    <div>
        <div class="profileset">
            <div class="container-about">
                    <span><h3>Biodata:</h3></span>
                    <span>Full Name: Luqman Maulana Rizki</span>
                    <span>Birth Date: 21 May 2000</span>
                    <span>Location: Indonesia</span>
            </div>
            <div class="container-about">
                <div class="container-about">
                    <img class="pasfoto" src="{% static 'pasfoto.png' %}" alt="Luqman"/>
                </div>
            </div>
            <div  class="container-about">
                    <h3>About Me:</h3>
                        <p>Seorang mahasiswa Fasilkom UI yang tinggal di kosan daerah Kukusan Kelurahan. Mencoba menyelesaikan setiap tugasnya dengan baik. </p>
            </div>
        </div>
    </div> 
    </div>
{% endblock body %}
    

main/templates/skills.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div id="skills">
    <h1 class="h1-title"><u>Skills</u></h1>
        <table class="skill-table">
            <tr class="row">
                <td>Python</td>
                <td>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star unchecked"></span>     
                </td>
            </tr>
            <tr class="row">
                <td>Java</td>
                <td>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star unchecked"></span>
                </td>
            </tr>
            <tr class="row">
                <td>HTML</td>
                <td>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </td>
            </tr>
            <tr class="row">
                <td>CSS</td>
                <td>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </td>
            </tr>
        </table>      
</div>
{% endblock body %}
    

story5/templates/jadwal.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <div class="jadwal">
        <h1 class="h1-title">Buat Jadwal</h1>
        <form action="{% url 'Story_5:jadwal' %}" method="POST">
            {% csrf_token %}
            <!-- <div class="form">
                <div class="container-name">
                <p class="form-name">Nama        </p>
                <p class="form-name">Tempat      </p>
                <p class="form-name">Kategori    </p>
                <p class="form-name">Hari        </p>
                <p class="form-name">Tanggal     </p>
                <p class="form-name">Waktu       </p>
                </div>
                <div class="form-input">
                    <input type="text" name="form.nama.name" id="form.nama.id_for_label"/>
                    <input type="text" name="form.tempat.name" id="form.tempat.id_for_label"/>
                    <input type="text" name="form.kategori.name" id="form.kategori.id_for_label"/>
                    <input type="text" name="form.hari.name" id="form.hari.id_for_label"/>
                    <input type="date" name="form.tanggal.name" id="form.tanggal.id_for_label"/>
                    <input type="time" name="form.waktu.name" id="form.waktu.id_for_label"/>
                </div>
            </div> -->
            {{ form.as_p}}
            <input type="submit" value="Submit"/>        
        </form>
    </div>
{% endblock body %}
    

story5/templates/lihat_jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="tabel-head">
        <div class="tabel">
            <div class="tabel-isi">Nama</div>
            <div class="tabel-isi">Tempat</div>
            <div class="tabel-isi">Kategori</div>
            <div class="tabel-isi">Tanggal</div>
            <div class="tabel-isi">Waktu</div>
        </div>
        {% for jadwal in jadwals %}
        <div class="tabel">
            <div class="tabel-isi">{{jadwal.nama}}</div>
            <div class="tabel-isi">{{jadwal.tempat}}</div>
            <div class="tabel-isi">{{jadwal.kategori}}</div>
            <div class="tabel-isi">{{jadwal.tanggal}}</div>
            <div class="tabel-isi">{{jadwal.waktu}}</div>
            <div class="tabel-delete"><a href="{% url 'Story_5:delete' jadwal.id %}" title=''>Delete</a></div>
        </div>
        {%endfor%}
        
    </div>
{% endblock body %}
    